version: '3.9'
services:
  playground:
    build:
      context: .
      target: playground
    container_name: python-playground
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/project